Created tests for 'UserData' & 'PostData'. Created Enums for 'Gender'…
GDGVizag/NowInGoogle pull request #2
Opened 2023-07-21 16:51 UTC by sreetejadusi

1. Written tests for adding a user and pulling user data.
2. Written tests for adding a Post and pulling a post data.
3. Implemented the above tests.
4. Created enums for `RegistrationStatus`, and `Gender`
5. Created the following classes and models: `Event`, `Post`, and `User`.

2023-07-22 08:04 UTC, sampathbalivada approved these changes
LGTM!

Good work @sreetejadusi ✌️

2023-07-22 08:09 UTC, sampathbalivada commented
@sreetejadusi can you squash all the commits into a single commit?

2023-07-23 11:57 UTC, ManasMalla requested changes
There are many issues to be address before we actually go ahead and push the code @sampathbalivada @sreetejadusi

2023-07-23 11:57 UTC, ManasMalla commented on lib/data/datasources/post_datastore.dart
@sreetejadusi can we extract out the logic for extracting the model from FirestoreDocument with the help of a secondary constructor of the model itself?

2023-07-23 11:57 UTC, ManasMalla commented on lib/data/datasources/post_datastore.dart
I believe the datasource should be responsible for fetching the data and the model should be responsible for creating its instance from the fetched data and not the datasource being responsible.

2023-07-23 11:57 UTC, ManasMalla commented on lib/data/datasources/post_datastore.dart
And yeah there are few issues with this code:
If you are throwing the Left(Failure()) then we will face an exception and the app will crash becuase bloc doesnt handle exceptions instead we wrap the exception with a class using the onCatch and mitigate that to a blocState.
**So there are two ways going forward:**
1. Change the return type of the datasource functions from `Future<Either<Failure, PostModel>>` to `Future<PostModel>` and still throw the error as an `Exception` which implements the `Exception` class of Flutter and translate the exception to a `Failure` in the repository, which is the preferred solution. As we might have a lot of exceptions being thrown in the datasource but you'rent mapping them all.
or
2. Change the keyword `throw` to `return` instead and handle all of the possible excpetions.

2023-07-23 11:57 UTC, ManasMalla commented on lib/data/datasources/user_datastore.dart
Can the need for searchUser() function be shared because the more the number of queries we run on `Firebase Firestore` the more econmical it can become?

2023-07-23 11:57 UTC, ManasMalla commented on lib/data/models/event_model.dart
@sampathbalivada yup, I believe we need a way to identify who is organizing this event. We need a bit of description about the event. We need the time of the event and the location/online/hybrid status of the event. and a parameter probably to hold other data specific to the event.

2023-07-23 11:57 UTC, ManasMalla commented on lib/data/models/post_model.dart
We need to once discuss about this!

2023-07-23 11:57 UTC, ManasMalla commented on lib/data/models/user_model.dart
We need to add userRole field in here, their age, avatar (if possible), cover and a list of their articles, their events, and their interests, following and followers and probably a short bio.

2023-07-23 11:57 UTC, ManasMalla commented on lib/domain/entities/enums/registration_status_enum.dart
Let's go ahead and even add `Attended` which will be the status once our volunteer scans their QR at the venue or attend our online event. And probably one more state, `PerksGiven`.

2023-07-23 11:57 UTC, ManasMalla commented on lib/data/models/event_model.dart
Where are we mapping the registratration status of a particular event?

2023-07-23 11:57 UTC, ManasMalla commented on lib/main.dart
We'd need to add the darkColorScheme under `darkTheme` and lightColorScheme for the `theme`

2023-07-23 11:57 UTC, ManasMalla commented on test/data/datasources/post_datastore_test.dart
@sreetejadusi I believe this is not how the test is to be drafted, here you are writing your custom implementation for your function and just calling it again instead, you should mock the firebase function to return the custom data and then test if our data source has been written well that it fetches the exact data by calling the right function with the right data. Mocking a function and calling the same function would definetely give the right results. @sampathbalivada What do you opine?

2023-07-23 11:57 UTC, ManasMalla commented on test/data/datasources/user_datastore_test.dart
The same thing here too, the data source test must test if the data source is working well with the dependency it is working on. @sreetejadusi one more important factor you forgot when coding, the code structure currently is very struck to the implementation. You didn't imply dependency injection. It hits us hard on the long run.

2023-07-23 12:09 UTC, sreetejadusi commented on lib/data/datasources/post_datastore.dart
Fixed.

2023-07-23 12:10 UTC, sreetejadusi commented on lib/data/datasources/user_datastore.dart
Can you please elaborate?

2023-07-23 12:14 UTC, sreetejadusi commented on lib/main.dart
It already exists, @ManasMalla. Were you referring to something else?
<img width="710" alt="image" src="https://github.com/GDGVizag/NowInGoogle/assets/67823025/cac21c8f-8fe4-44ff-a0ba-ace88b795be6">

2023-07-23 12:24 UTC, sreetejadusi commented on lib/data/models/user_model.dart
What types of UserRoles would you suggest? I would say `Admin`, `Volunteer`, and `Member`; The question is about `Speaker` if it should have a special role for itself or take the role of a `Volunteer` and display a `Speaker` badge with the approval of an `Admin`.

2023-07-23 12:48 UTC, ManasMalla commented on lib/data/datasources/user_datastore.dart
I meant what does the searchUser() function do?

2023-07-23 12:49 UTC, ManasMalla commented on lib/data/models/user_model.dart
Yeah admin, volunteer, `attendee` and let's I guess speaker would be an attendee with a special tag of speaker, rather than of a volunteer with a tag.

2023-07-23 12:50 UTC, ManasMalla commented on lib/main.dart
Oh then that's great, the git diff log didn't show that 😄

2023-07-23 12:51 UTC, ManasMalla commented on lib/data/datasources/post_datastore.dart
Pushed with the fixes? @sreetejadusi

2023-07-23 12:52 UTC, sreetejadusi commented on lib/data/models/user_model.dart
User class modified.

2023-07-23 12:54 UTC, sreetejadusi commented on lib/domain/entities/enums/registration_status_enum.dart
Done.

2023-07-23 13:25 UTC, sreetejadusi commented on lib/data/models/user_model.dart
I think `Member` would make more sense rather than `Attendee` because attendee refers as a person attending the events and `Member` refers as someone who is a member of a community. What would you suggest @sampathbalivada ?

2023-07-23 13:33 UTC, sreetejadusi commented on test/data/datasources/user_datastore_test.dart
Yes @ManasMalla. That was a silly mistake. It is now fixed in the commit 4aa7003

2023-07-23 13:36 UTC, sreetejadusi commented on lib/data/models/user_model.dart
It remains as 'Member' as of now, and I assure you that changes will be made upon unanimous agreement.

2023-07-23 18:01 UTC, ManasMalla commented on test/data/datasources/user_datastore_test.dart
@sreetejadusi man another silly mistake, you injected the dependencies, but you forgot to change the when() mock to mock the MockFirebaseFirestore dependencies 😂

2023-07-24 18:16 UTC, closed without merging